name: deploy_to_vcs
on:
  workflow_dispatch:

jobs:
  run_tests:
    uses: ./.github/workflows/test.yml
    secrets:
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
   
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Download code"
        uses: actions/checkout@v4

      - name: "Copy files to VPS"
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "."
          target: "~/fastapi_boilerplate"

      - name: "Make envfile"
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          envkey_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}     
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}      
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} 
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_ALGORITHM: ${{ secrets.ALGORITHM }}
          envkey_ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          directory: .
          file_name: .env
          fail_on_empty: false
          sort_keys: false          

      - name: Stop containers
        run: docker compose down

      - name: Build images
        run: docker compose build --no-cache

      - name: Start services
        run: docker compose up -d

      - name: Show container status
        run: docker compose ps          