name: deploy_to_vcs
on:
  workflow_dispatch:

jobs:
  run_tests:
      uses: ./.github/workflows/test.yml
      secrets:
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALGORITHM: ${{ secrets.ALGORITHM }}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
   
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Download code"
        uses: actions/checkout@v4

      - name: "Copy files to VPS"
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "~/fastapi_boilerplate"